### ISSUE TITLE
Compression Artifacts hevc-nvec and hevc-cuvid at beginning of GOP

### ISSUE THREAD

**Issue by erichorwitz** [CESNET/UltraGrid#114]
I am getting what looks to be a compression artifact on the full frame that happens at either the beginning or end, i cant tell which, of the GOP structure. I am using NVEC encoding and decoding on both ends with Libavcodec. I know it follows the GOP structure because If I change the length of the GOP it follows it. Every second for GOP=24, every 2 seconds for GOP=48.

I do not notice this problem on the software decoder of Libavcodec. Its easiest to see when you park on a frame from the sender it becomes visually apparent. During normal playback its hard to see visually but on a scope its very apparent.

**Comment by alatteri** [comment]
Does it look like that single frame is a real low bitrate JPEG?  I've seen that too with dark grainy material.

**Comment by MartinPulec** [comment]
Hi Eric, this is known issue - I suppose that it is on the beginning of the GOP when lower-quality I-frame is sent that is subsequently improved with further P-frames.

Would you be able to try different rate-control algorithms (`rc=<RC>`)? List of available ones can be issued by `-c libavcodec:encoder=h264_nvenc:help`. Also `spatial_aq` or `temporal_aq` options may help.

Alternatively, if you want, I can try to tweak the parameters by myself - may I ask you for some (static) image that I can use for test, I currently don'ŧ have a content - AFAIK page with a text is good for that, but perhaps a more representative content would be sufficient.

**Comment by alatteri** [comment]
Hi Martin,

I don't see a specific parameter to enable intra-refresh with NVENC. I have found that in other codecs, using intra-refresh helped to remove this artifact.  I believe the under-lying NVENC API supports this, but I'm not sure if that was implemented in the FFMPEG implementation.

Alan

**Comment by MartinPulec** [comment]
Hi @alatteri, your observations are correct - NVENC provides an intra-refresh option but FFmpeg doesn't publish that. Some time ago I've played with it a bit and it didn't improve that behavior much.

But maybe it is time to recheck the situation again? I am not sure if anyone has some experience with submitting patches to FFmpeg, but at least I could patch it in UG's binary distributions (Win, mac bundle, AppImage). Of course only if it improves the situation (in addition it would require custom Win and mac FFmpeg builds - currently only Linux uses own FFmpeg build).

**Comment by alatteri** [comment]
There does seem to be some code here relating to IntraRefresh with NVENC.  But it is old.

https://ffmpeg.org/doxygen/3.2/nvEncodeAPI_8h_source.html

**Comment by MartinPulec** [comment]
FYI, the current version is here:

https://git.videolan.org/?p=ffmpeg/nv-codec-headers.git;a=blob_plain;f=include/ffnvcodec/nvEncodeAPI.h;hb=HEAD

So it is still there - but as I've written, some time ago when I've tried to set the intra-refresh, it didn't have a significant impact on that particular behavior. But I think that it might have changed with subsequent NVIDIA cards (supposing that this feature is hard-wired on the chip).

**Comment by alatteri** [comment]
[pulsing.00088919.tif.zip](https://github.com/CESNET/UltraGrid/files/5699244/pulsing.00088919.tif.zip)

This is a sample frame that exhibits pulsing in many codec scenarios.

**Comment by alatteri** [comment]
I would be totally fine if it was only patched in the Linux build.  At least we could start there.  In my experience, with x265, intra-refresh completely eliminated all GOP pulsing.  

> I could patch it in UG's binary distributions (Win, mac bundle, AppImage). Of course only if it improves the situation (in addition it would require custom Win and mac FFmpeg builds - currently only Linux uses own FFmpeg build).

**Comment by MartinPulec** [comment]
> In my experience, with x265, intra-refresh completely eliminated all GOP pulsing.

The problem is that I didn't get it work in the past, or more precisely it didn't look like to have any effect. Perhaps I could had set it in a wrong way? It is also possible that the device I've tried with didn't support the intra-refresh. In the bellow patch, there should be a check.

Anyways, I've created a FFmpeg patch ([nvenc-intra-refresh.patch.txt](https://github.com/CESNET/UltraGrid/files/5807889/nvenc-intra-refresh.patch.txt)), that unconditionally (for the time being) enables intra-refresh for NVENC. As I said, I am not 100% sure it is correct. Would anyone be able to check if it makes any difference?

References: [1](https://forums.developer.nvidia.com/t/nvenc-hevc-and-intra-refresh/69481) [2](https://git.videolan.org/?p=ffmpeg/nv-codec-headers.git;a=blob;f=include/ffnvcodec/nvEncodeAPI.h;h=4b0c9ff97caaef1fe51bf36d0560dad2c7a8a3df;hb=HEAD) [3](https://on-demand.gputechconf.com/gtc/2014/presentations/S4654-detailed-overview-nvenc-encoder-api.pdf)

**Comment by alatteri** [comment]
Thanks Martin.....I'll give it a try, will take me a few days at least to get things setup.  I normally use OS provided libavcodec packages.

**Comment by MartinPulec** [comment]
Not sure if it helps, but branch [ffmpeg-nvenc in my repo](https://github.com/MartinPulec/UltraGrid/tree/ffmpeg-nvenc) has the change integrated in CI. The respective build is [here](https://github.com/MartinPulec/UltraGrid/actions/runs/482887189) bellow. I've modified/added the workflow file that it triggers the rebuild in branch _ffmpeg-nvenc_ in any repo.

**Comment by alatteri** [comment]
Great....this will help alot.

**Comment by MartinPulec** [comment]
Okay, the proposed changes didn't work. Does some of you guys have some idea what could be set for the intra refresh?

Currently I am setting `enableIntraRefresh` to 1, `intraRefreshPeriod` to some GOP, let say 25 and `intraRefreshCnt` to 24. `gopLength` should be AFAIK `NVENC_INFINITE_GOPLENGTH`. But that perhaps requires `idrPeriod` to be set to 25, not infinite - otherwise the decoder won't resynchronize in the middle of the stream.

This set doesn't seem to work as Alan reported. It look to me that it would require also the `idrPeriod` to be set to infinite. Which is unfortunately unsuitable for UG. Otherwise I am afraid that it cannot be fixed.

**Comment by alatteri** [comment]
Would be worth trying newer nvcodec headers in **only** that branch just to see?

**Comment by MartinPulec** [comment]
Why not, I've pushed the build  [here](https://github.com/MartinPulec/UltraGrid/actions/runs/515236150), we will see. But it would surprise me, although I cannot be 100% sure - there will be differences at least with different presets. But unless it is dependent on that, I would not see anything much different.

B frames should be unconditionaly disabled by UG, see [here](https://github.com/CESNET/UltraGrid/blob/cf9f6a468cfda1a951b1e2d742f9193bded43151/src/video_compress/libavcodec.cpp#L714). But a good point, I'll check FFmpeg if it reflects that. But most likely so.

**Comment by MartinPulec** [comment]
Okay, so I've looked in the FFmpeg code and B frames set to 0 result to frameIntervalP==1 which should disable B frames. Also there is in headers:

    Presets P3 to P7 for H264 and Presets P2 to P7 for HEVC have B frames enabled by default [...] In case Weighted Prediction is required, disable B frames by setting frameIntervalP = 1

So setting preset to `P1` would disable B-frames with the preset itself, but it should not be needed with the above setting.

**Comment by alatteri** [comment]
Thanks Martin....I try to test this today or tomorrow.

**Comment by alatteri** [comment]
This build did not change the behavior.  Intra-refresh still not working.   

Are there any other settings that might help minimize the pulsing in the standard GOP mode?

> Why not, I've pushed the build [here](https://github.com/MartinPulec/UltraGrid/actions/runs/515236150), we will see. But it would surprise me, although I cannot be 100% sure - there will be differences at least with different presets. But unless it is dependent on that, I would not see anything much different.
> 
> B frames should be unconditionaly disabled by UG, see [here](https://github.com/CESNET/UltraGrid/blob/cf9f6a468cfda1a951b1e2d742f9193bded43151/src/video_compress/libavcodec.cpp#L714). But a good point, I'll check FFmpeg if it reflects that. But most likely so.

**Comment by MartinPulec** [comment]
> Are there any other settings that might help minimize the pulsing in the standard GOP mode?

You may try to use `rc=constqp` or `rc=vbr` (and if using the intra-refresh build, then also `:disable_intra_refresh`). Unless there is no need to keep the bitrate steady (on per-frame basis), it is quite easy.

**Comment by MartinPulec** [comment]
Also it helps to increase the bitrate if possible - `bpp=0.5` looks quite usable (default is 0.28 for H.264), it however leads to some 30 Mbps for 1080p.

One more thing, however, is unclear to me - @erichorwitz, are you sure that this behavior occurs with NVDEC and not SW decoder for the same stream? I haven't checked this yet but if so, it needs to be investigated, for sure. If you could provide sample picture that shows that + encoding parameters, it would be great.

**Comment by erichorwitz** [comment]
@MartinPulec i will try and set up a test for this. Just for reference though, the easiest way to see the strobing is with a scope.

**Comment by alatteri** [comment]
@MartinPulec I uploaded a tif file in comment fromDec. 15th. that gives strobing both visually and on scope.

**Comment by erichorwitz** [comment]
@alatteri was this tiff from a software decoder or the Nvenc Decoder?

**Comment by alatteri** [comment]
Its a source file exported from one of our Flames.

**Comment by MartinPulec** [comment]
Hi guys, do you have some follow-ups? Sorry @alatteri that I've not responded, I've somehow forgot but 2 things:
1. I can see from the tiff just a single frame, which I don't see anything wrong - is it a multi-picture TIFF (like animated GIF or MJPEG)?
2. from your description it seems to be the known issue with NVENC pulsation, or am I wrong (mentioned for instance in #244 and #289)?
    as for this, intra-refresh is already enabled in UG (at least in Linux builds) but it doesn't seem to help much unless you set `--param --param lavc-rc-buffer-size-factor=0` (or a different value >1.0, eg. 2 meaning that IDR frame will be at most twice as bigger than specified by the codec bitrate)

Anyways, I am not sure if @erichorwitz meant this issue. I believe that it was rather about NVDEC (cuvid) _decode_, in which case it would be better not to use NVENC for the report but rather libx264. If so and still relevant, please check if the issue is present when using _libx264_ encoder to rule out an issue in encoder.

**Comment by alatteri** [comment]
Hi Martin,

I'm not currently using NVENC as the work you did to enable HW compression for NUC12+ is adequate for our 4K needs. Thanks for that BTW.  Although now that [Intel has canceled NUC product line](https://www.theverge.com/2023/7/11/23790956/intel-nuc-compact-pc-discontinued), I may at some point need to go back to NVENC.

In regards to the TIFF, no it is a single frame, to be used as a source input.  It is not a capture of the output.  In my previous testing, there is something in that TIFF (the dark tones along with the heavy film grain/noise) , that if used as input for signal to NVENC would cause the GOP pulsations.

**Comment by MartinPulec** [comment]
Thanks for the info, @alatteri. Actually it seems that [Asus will take the NUC line over](https://www.intel.com/content/www/us/en/newsroom/news/intel-nuc-systems-agreement.html), we will see how it develops.

> In regards to the TIFF, no it is a single frame, to be used as a source input

Ok, I understand. To this topic, as already mentioned otherwhere,  `--param lavc-rc-buffer-size-factor=0` (or a factor something between 3 and 10) would help. But it has some negative side effects, notably that the IDR frames can be as much as N-times (given by the factor) bigger than other frames (so also it will have higher bitrate that time). I've spent some time with this and it seems to me that there is nothing that can be done about it - I think that the intra-refresh in the NVIDIA implementation requires infinite GOP, which is unsuitable for UG. If not, every IDR frame is a full I-frame, effectively eliminating intra-refresh, because we need IDR frames to start decode from (curiously x264/5 seem to be able to reference pre-IDR data so that even IDR frame hold just one "intra" bar, not the whole picture).

But we could rather open another issue for that – I recall that this problem was mentioned more times elsewhere but I didn't find an issue _specifically_ on this topic.

Anyways, as I've looked back this issue, I am still not 100% sure if it is _the_ problem. Specifically, @erichorwitz has written in first post that he had not noticed the problem with software decoder. The pulsation, however, should be observable also with SW decoder – I've just checked that I can't see any difference between _hevc_ and _hevc_cuvid_ using the picture linked above (both pulsated with lower rc-buffer-size-factor).

**Comment by MartinPulec** [comment]
Ok, I've made couple of changes in this field, namely:

1. for _h264\_nvenc_, I've made a workaround that caused the pulsation has entirely gone
2. for _hevc\_nvenc_ (and also _av1\_nvenc_) I've disabled the intra-refresh+frame size restrictions altogether by default. As a side-effect, the I-frames are significantly bigger than P-frames (that's why we mostly insist on intra-refresh in UG if possible). It of course depends on network conditions whether it is a problem
3. for _hevc\_nvenc_ (**but not** _av1\_nvenc_), intra-refresh can be enabled by `:intra-refresh`. It uses the same workaround as point 1. It is not enabled by default because under some specific conditions (static content) it may produce artifacts because the infinite-GOP is used and the NVIDIA encoder doesn't send a reference picture never again in such cases.
4. the original behavior can be perhaps emulated by `--param lavc-rc-buffer-size-factor=1.5` (it doesn't set intra-refresh for HEVC/AV1 but the size restrictions should behave actually the same).
